/**
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input: s = "abcd" t = "abcde"
 * 
 * Output: e
 * 
 * Explanation: 'e' is the letter that was added.
 * 
 * @author zhugr
 *
 */
public class Solution {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
	}

	public char findTheDifference(String s, String t) {
		int[] ss = new int[26];
		int[] tt = new int[26];
		int lens = s.length();
		int lent = t.length();
		for(int i = 0; i < lens; ++i)
			++ss[s.charAt(i) - 'a'];
		for(int i = 0; i < lent; ++i)
			++tt[t.charAt(i) - 'a'];
		int i;
		for(i = 0; i < 26; ++i){
			if(tt[i] - ss[i] == 1)
				break;
		}
		return (char)('a' + i);
	}
}
